/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Înregistrare utilizator nou */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentificare cu email și parolă */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deconectare (distruge sesiunea) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profilul utilizatorului autentificat */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trimite codul de verificare a emailului */
        post: operations["AuthController_emailVerifySend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/verify/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmă emailul cu codul primit */
        post: operations["AuthController_confirmEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicită resetarea parolei */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resetează parola cu codul primit pe email */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDto: {
            /**
             * @description Adresa de email a utilizatorului
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Identificatorul unic al utilizatorului (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * Format: date-time
             * @description Data și ora la care a fost creat contul
             * @example 2026-07-24T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data și ora ultimei actualizări a contului
             * @example 2026-07-24T12:30:00.000Z
             */
            updatedAt: string;
            /**
             * @description Dacă adresa de email a fost confirmată
             * @example false
             */
            isVerified: boolean;
            /**
             * @description Prenumele utilizatorului
             * @example Ion
             */
            firstName: string | null;
            /**
             * @description Numele de familie al utilizatorului
             * @example Popescu
             */
            lastName: string | null;
        };
        AuthUserDataDto: {
            /** @description Profilul utilizatorului autentificat */
            user: components["schemas"]["UserDto"];
        };
        RegisterPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a noului cont
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Parola contului (minim 8 caractere, litere mari/mici, cifră și caracter special)
             * @example Password123!
             */
            password: string;
        };
        ErrorResponseDto: {
            /**
             * @description Indică un răspuns de eroare
             * @example false
             * @enum {boolean}
             */
            success: false;
            /**
             * @description Codul HTTP al erorii
             * @example 422
             */
            statusCode: number;
            /**
             * @description Mesaj human-readable, gata de afișat global
             * @example Validation failed
             */
            message: string;
            /**
             * @description Erori pe câmp. null când eroarea nu e legată de câmpuri.
             * @example {
             *       "email": [
             *         "Adresa de email nu este validă"
             *       ],
             *       "password": [
             *         "Parola trebuie să aibă minim 8 caractere"
             *       ]
             *     }
             */
            details: {
                [key: string]: string[];
            } | null;
            /**
             * @description Meta informații utile pentru debugging
             * @example {
             *       "path": "/auth/login",
             *       "timestamp": "2026-07-27T08:00:00.000Z"
             *     }
             */
            meta: {
                path?: string;
                /** Format: date-time */
                timestamp?: string;
            };
        };
        LoginPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a contului
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Parola contului
             * @example Password123!
             */
            password: string;
        };
        MessageDataDto: {
            /** @description Mesaj descriptiv pentru client */
            message: string;
        };
        TokenSentDataDto: {
            /** @description Mesaj descriptiv pentru client */
            message: string;
            /**
             * @description Data de expirare a tokenului (ISO), utilă pentru countdown în frontend
             * @example 2026-07-27T08:05:00.000Z
             */
            tokenExpiresAt: string;
        };
        ConfirmEmailPayloadDto: {
            /**
             * @description Codul OTP de 6 cifre primit pe email
             * @example 123456
             */
            token: string;
        };
        ForgotPasswordPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email pentru care se solicită resetarea parolei
             * @example test@gmail.com
             */
            email: string;
        };
        ResetPasswordPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a contului
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Codul OTP de 6 cifre primit pe email
             * @example 123456
             */
            token: string;
            /**
             * @description Noua parolă (minim 8 caractere, litere mari/mici, cifră și caracter special)
             * @example NewPassword123!
             */
            newPassword: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayloadDto"];
            };
        };
        responses: {
            /** @description Utilizator creat și sesiune inițiată */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 201
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Conflict la înregistrare */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayloadDto"];
            };
        };
        responses: {
            /** @description Autentificare reușită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Credențiale invalide */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deconectare reușită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["MessageDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profilul utilizatorului din sesiune */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_emailVerifySend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cod de verificare trimis pe email */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["TokenSentDataDto"];
                    };
                };
            };
            /** @description Email deja confirmat / token încă valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_confirmEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailPayloadDto"];
            };
        };
        responses: {
            /** @description Email confirmat cu succes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["MessageDataDto"];
                    };
                };
            };
            /** @description Cod invalid / expirat */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordPayloadDto"];
            };
        };
        responses: {
            /** @description Răspuns generic (email trimis dacă adresa există) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["TokenSentDataDto"];
                    };
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordPayloadDto"];
            };
        };
        responses: {
            /** @description Parola a fost resetată */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["MessageDataDto"];
                    };
                };
            };
            /** @description Cod invalid / expirat */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
