import { writeFile } from "node:fs/promises"
import openapiTS, { astToString } from "openapi-typescript"
import ts from "typescript"

/**
 * Generatorul default mapează `format: binary` la `string`, ceea ce face
 * imposibilă tiparea corectă a upload-urilor (`avatarFile` primește un `File`).
 * Hook-ul `transform` de mai jos emite `Blob`, ca fișierul generat să nu mai
 * necesite corecturi manuale după fiecare `npm run generate:api`.
 */
const BLOB = ts.factory.createTypeReferenceNode("Blob")
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull())

const SCHEMA_URL = process.env.SWAGGER_URL ?? "http://localhost:5000/swagger/json"
const OUTPUT_PATH = new URL("../src/shared/api/v1.d.ts", import.meta.url)

const ast = await openapiTS(new URL(SCHEMA_URL), {
  transform(schemaObject) {
    if (schemaObject.format === "binary") {
      return schemaObject.nullable ? ts.factory.createUnionTypeNode([BLOB, NULL]) : BLOB
    }
  },
})

const header = [
  "/**",
  " * This file was auto-generated by openapi-typescript.",
  " * Do not make direct changes to the file.",
  " */",
  "",
].join("\n")

await writeFile(OUTPUT_PATH, `${header}\n${astToString(ast)}`)

console.log(`✔ ${SCHEMA_URL} → src/shared/api/v1.d.ts`)
