/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Încarcă avatarul utilizatorului autentificat
         * @description Acceptă un fișier imagine (`avatarFile`) via `multipart/form-data`. Tipurile permise și dimensiunea maximă sunt configurabile prin variabile de mediu.
         */
        post: operations["UsersController_uploadAvatar_v1"];
        /** Șterge avatarul utilizatorului autentificat */
        delete: operations["UsersController_deleteAvatar_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizează profilul utilizatorului autentificat
         * @description Actualizează câmpurile din `user_profiles` pentru userul din sesiune și returnează doar profilul public (`UserProfileDto`).
         */
        patch: operations["UsersController_updateProfile_v1"];
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesiunile active ale utilizatorului autentificat */
        get: operations["SessionController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deconectează celelalte dispozitive */
        delete: operations["SessionController_revokeOthers_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocă o sesiune anume */
        delete: operations["SessionController_revoke_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Înregistrare utilizator nou
         * @description Creează contul, inițiază sesiunea și returnează userul public. `user.profile` este `null` aici (profilul se citește pe GET /auth/me).
         */
        post: operations["AuthController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentificare cu email și parolă
         * @description Validează credențialele, regenerează sesiunea și returnează userul public. `user.profile` este `null` aici (profilul se citește pe GET /auth/me).
         */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deconectare (închide sesiunea curentă) */
        post: operations["AuthController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profilul utilizatorului autentificat
         * @description Returnează contul curent împreună cu profilul nested (`user.profile`), spre deosebire de register/login unde relația nu este încărcată.
         */
        get: operations["AuthController_getMe_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicită resetarea parolei */
        post: operations["AuthController_forgotPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resetează parola cu codul primit pe email */
        post: operations["AuthController_resetPassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponseDto: {
            /**
             * @description Indică un răspuns de eroare
             * @example false
             * @enum {boolean}
             */
            success: false;
            /**
             * @description Codul HTTP al erorii
             * @example 422
             */
            statusCode: number;
            /**
             * @description Mesaj human-readable, gata de afișat global
             * @example Validation failed
             */
            message: string;
            /**
             * @description Erori pe câmp. null când eroarea nu e legată de câmpuri.
             * @example {
             *       "email": [
             *         "Adresa de email nu este validă"
             *       ],
             *       "password": [
             *         "Parola trebuie să aibă minim 8 caractere"
             *       ]
             *     }
             */
            details: {
                [key: string]: string[];
            } | null;
            /**
             * @description Meta informații utile pentru debugging
             * @example {
             *       "path": "/auth/login",
             *       "timestamp": "2026-07-27T08:00:00.000Z"
             *     }
             */
            meta: {
                path?: string;
                /** Format: date-time */
                timestamp?: string;
            };
        };
        UserProfileDto: {
            /**
             * @description Prenumele
             * @example Ion
             */
            firstName: string | null;
            /**
             * @description Numele de familie
             * @example Popescu
             */
            lastName: string | null;
            /**
             * @description URL-ul avatarului
             * @example https://cdn.example.com/avatars/ion.png
             */
            avatarUrl: string | null;
            /**
             * @description Locația (oraș / țară)
             * @example Chișinău, Moldova
             */
            location: string | null;
            /**
             * @description Titlul / funcția profesională
             * @example Software Engineer
             */
            jobTitle: string | null;
            /**
             * @description Descriere scurtă (bio)
             * @example Pasionat de NestJS și TypeScript.
             */
            bio: string | null;
        };
        UserProfileDataDto: {
            /** @description Profilul public actualizat */
            profile: components["schemas"]["UserProfileDto"];
        };
        UpdateUserAvatarPayloadDto: {
            /**
             * Format: binary
             * @description Fișier imagine (JPEG, PNG, WebP sau GIF), maxim 2 MB
             */
            avatarFile: Blob;
        };
        UpdateUserProfilePayloadDto: {
            /**
             * @description Prenumele
             * @example Ion
             */
            firstName?: string;
            /**
             * @description Numele de familie
             * @example Popescu
             */
            lastName?: string;
            /**
             * @description Locația (oraș / țară)
             * @example Chișinău, Moldova
             */
            location?: string;
            /**
             * @description Titlul / funcția profesională
             * @example Software Engineer
             */
            jobTitle?: string;
            /**
             * @description Descriere scurtă (bio)
             * @example Pasionat de NestJS și TypeScript.
             */
            bio?: string;
        };
        DeviceDataDto: {
            /**
             * @description Adresa IP de la care s-a autentificat utilizatorul
             * @example 82.76.14.201
             */
            ip: string;
            /**
             * @description Browserul detectat din User-Agent
             * @example Chrome
             */
            browser: string;
            /**
             * @description Versiunea browserului
             * @example 141.0.0.0
             */
            browserVersion: string;
            /**
             * @description Sistemul de operare detectat
             * @example Linux
             */
            os: string;
            /**
             * @description Platforma detectată
             * @example Desktop
             */
            platform: string;
            /**
             * @description Dacă sesiunea a fost pornită de pe un dispozitiv mobil
             * @example false
             */
            isMobile: boolean;
            /**
             * @description Dacă sesiunea a fost pornită de pe un desktop
             * @example true
             */
            isDesktop: boolean;
            /**
             * @description Momentul autentificării (ISO)
             * @example 2026-09-18T06:00:00.000Z
             */
            loggedAt: string;
            /**
             * @description Ultima activitate înregistrată pe sesiune (ISO)
             * @example 2026-09-18T06:42:00.000Z
             */
            lastActiveAt: string;
        };
        ActiveSessionDto: {
            /** @description Metadatele dispozitivului; null pentru sesiuni mai vechi, fără metadate. */
            deviceData: components["schemas"]["DeviceDataDto"] | null;
            /**
             * @description Identificator public al sesiunii, folosit la revocare
             * @example 9f2c4b7e1a83d5460bc2e7f0a1d93c58
             */
            id: string;
            /**
             * @description Secundele rămase până la expirarea sesiunii
             * @example 2591640
             */
            expiresInSeconds: number;
            /**
             * @description `true` pentru sesiunea din care vine request-ul curent
             * @example true
             */
            isCurrent: boolean;
        };
        ActiveSessionsDataDto: {
            /** @description Sesiunile active, cea curentă fiind prima în listă */
            sessions: components["schemas"]["ActiveSessionDto"][];
        };
        RevokedSessionsDataDto: {
            /** @description Mesaj descriptiv pentru client */
            message: string;
            /**
             * @description Numărul de sesiuni închise
             * @example 2
             */
            revoked: number;
        };
        UserDto: {
            /** @description Profilul public nested. null pe login/register; populat pe GET /auth/me. */
            profile: components["schemas"]["UserProfileDto"] | null;
            /**
             * @description Identificatorul unic al utilizatorului (UUID)
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Adresa de email a utilizatorului
             * @example test@gmail.com
             */
            email: string;
            /**
             * Format: date-time
             * @description Data și ora la care a fost creat contul
             * @example 2026-07-24T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data și ora ultimei actualizări a contului
             * @example 2026-07-24T12:30:00.000Z
             */
            updatedAt: string;
        };
        AuthUserDataDto: {
            /** @description Utilizatorul public. Pe /auth/me include profile; pe register/login profile este null. */
            user: components["schemas"]["UserDto"];
        };
        RegisterPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a noului cont
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Parola contului (minim 8 caractere, litere mari/mici, cifră și caracter special)
             * @example Password123!
             */
            password: string;
        };
        LoginPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a contului
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Parola contului
             * @example Password123!
             */
            password: string;
        };
        MessageDataDto: {
            /** @description Mesaj descriptiv pentru client */
            message: string;
        };
        TokenSentDataDto: {
            /** @description Mesaj descriptiv pentru client */
            message: string;
            /**
             * @description Data de expirare a tokenului (ISO), utilă pentru countdown în frontend
             * @example 2026-07-27T08:05:00.000Z
             */
            tokenExpiresAt: string;
        };
        ForgotPasswordPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email pentru care se solicită resetarea parolei
             * @example test@gmail.com
             */
            email: string;
        };
        ResetPasswordPayloadDto: {
            /**
             * Format: email
             * @description Adresa de email a contului
             * @example test@gmail.com
             */
            email: string;
            /**
             * @description Codul OTP de 6 cifre primit pe email
             * @example 123456
             */
            token: string;
            /**
             * @description Noua parolă (minim 8 caractere, litere mari/mici, cifră și caracter special)
             * @example NewPassword123!
             */
            newPassword: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_uploadAvatar_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UpdateUserAvatarPayloadDto"];
            };
        };
        responses: {
            /** @description Avatar încărcat; profil actualizat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["UserProfileDataDto"];
                    };
                };
            };
            /** @description Fișier lipsă / invalid / prea mare */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_deleteAvatar_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar șters; profil actualizat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["UserProfileDataDto"];
                    };
                };
            };
            /** @description Nu există avatar de șters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_updateProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserProfilePayloadDto"];
            };
        };
        responses: {
            /** @description Profil actualizat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["UserProfileDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide / body gol */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista sesiunilor active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["ActiveSessionsDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionController_revokeOthers_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesiunile celorlalte dispozitive au fost închise */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["RevokedSessionsDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionController_revoke_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificatorul public al sesiunii (din GET /sessions) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesiunea a fost închisă */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["RevokedSessionsDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Sesiune inexistentă */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPayloadDto"];
            };
        };
        responses: {
            /** @description Utilizator creat și sesiune inițiată (profile: null) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 201
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Conflict la înregistrare */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayloadDto"];
            };
        };
        responses: {
            /** @description Autentificare reușită (profile: null) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Credențiale invalide */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deconectare reușită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["MessageDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_getMe_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilizator + profil nested din sesiune */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["AuthUserDataDto"];
                    };
                };
            };
            /** @description Neautentificat */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordPayloadDto"];
            };
        };
        responses: {
            /** @description Răspuns generic (email trimis dacă adresa există) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["TokenSentDataDto"];
                    };
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordPayloadDto"];
            };
        };
        responses: {
            /** @description Parola a fost resetată */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Indică un răspuns de succes
                         * @example true
                         * @enum {boolean}
                         */
                        success: true;
                        /**
                         * @description Codul HTTP al răspunsului
                         * @example 200
                         */
                        statusCode: number;
                        /** @description Meta informații utile pentru client */
                        meta: {
                            /** @example /auth/login */
                            path: string;
                            /**
                             * Format: date-time
                             * @example 2026-07-27T08:00:00.000Z
                             */
                            timestamp: string;
                        };
                        data: components["schemas"]["MessageDataDto"];
                    };
                };
            };
            /** @description Cod invalid / expirat */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Date invalide */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Prea multe cereri */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
